# ============================================
# APPLICATION
# ============================================
spring.application.name=MaisonNoir

# ============================================
# MYSQL DATABASE (Use environment variables)
# ============================================
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Turn off show SQL in production
#spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.show-sql=true
# init-mode=always (if using schema.sql and data.sql)
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.hbm2ddl=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# ============================================
# MONGODB CONFIGURATIONS
# ============================================
spring.data.mongodb.uri=${MONGODB_URI}

# ============================================
# ERROR HANDLING (preventing internal errors from leaking)
# ============================================
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never

# ============================================
# JWT (Use environment variables)
# ============================================
jwt.secret=${JWT_SECRET}
# 24 hours default
jwt.expiration=${JWT_EXPIRATION:86400000}

# ============================================
# SERVER
# ============================================
# Required for Render
server.port=${PORT:8080}
