# ============================================
# APPLICATION
# ============================================
spring.application.name=MaisonNoir

# ============================================
# MYSQL DATABASE (Use environment variables)
# ============================================
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
# Turn off show SQL in production
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ============================================
# MONGODB CONFIGURATIONS
# ============================================
spring.data.mongodb.uri=${MONGODB_URI}

# ============================================
# ERROR HANDLING (preventing internal errors from leaking)
# ============================================
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never

# ============================================
# JWT (Use environment variables)
# ============================================
jwt.secret=${JWT_SECRET}
# 24 hours default
jwt.expiration=${JWT_EXPIRATION:86400000}

# ============================================
# SERVER
# ============================================
# Required for Render
server.port=${PORT:8080}
